In [5]:
import numpy as np

In [6]:
from sklearn.datasets import load_iris

C:\Users\AmitKumar\.conda\envs\nlp_course\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
C:\Users\AmitKumar\.conda\envs\nlp_course\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [7]:
Iris = load_iris()

C:\Users\AmitKumar\.conda\envs\nlp_course\lib\site-packages\sklearn\datasets\base.py:242: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
C:\Users\AmitKumar\.conda\envs\nlp_course\lib\site-packages\sklearn\datasets\base.py:246: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you

In [8]:
print(Iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [9]:
X = Iris.data
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
Y = Iris.target
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
from keras.utils import to_categorical

In [12]:
Y = to_categorical(Y)

In [13]:
Y.shape

(150, 3)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 42)

In [16]:
X_train.shape

(105, 4)

In [17]:
Y_train.shape

(105, 3)

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler_object = MinMaxScaler()

In [21]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
scaled_x_train = scaler_object.transform(X_train)

In [23]:
scaled_x_test = scaler_object.transform(X_test)

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
model = Sequential()
model.add(Dense(8,input_dim = 4,activation ='relu'))
model.add(Dense(8,input_dim = 4,activation = 'relu'))
model.add(Dense(3,activation='softmax'))

In [31]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(scaled_x_train,Y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 0.8013 - accuracy: 0.6476 - 16ms/epoch - 4ms/step
Epoch 2/150
4/4 - 0s - loss: 0.7825 - accuracy: 0.6571 - 6ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 0.7512 - accuracy: 0.6667 - 9ms/epoch - 2ms/step
Epoch 4/150
4/4 - 0s - loss: 0.7176 - accuracy: 0.6857 - 11ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 0.6889 - accuracy: 0.7429 - 18ms/epoch - 4ms/step
Epoch 6/150
4/4 - 0s - loss: 0.6702 - accuracy: 0.8190 - 10ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 0.6572 - accuracy: 0.8571 - 14ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 0.6464 - accuracy: 0.8952 - 11ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 0.6356 - accuracy: 0.9238 - 12ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 0.6245 - accuracy: 0.9333 - 11ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 0.6129 - accuracy: 0.9333 - 12ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 0.6023 - accuracy: 0.9333 - 9ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 0.5920 - accuracy: 0.9

Epoch 104/150
4/4 - 0s - loss: 0.2556 - accuracy: 0.9714 - 9ms/epoch - 2ms/step
Epoch 105/150
4/4 - 0s - loss: 0.2532 - accuracy: 0.9714 - 11ms/epoch - 3ms/step
Epoch 106/150
4/4 - 0s - loss: 0.2505 - accuracy: 0.9714 - 11ms/epoch - 3ms/step
Epoch 107/150
4/4 - 0s - loss: 0.2491 - accuracy: 0.9714 - 12ms/epoch - 3ms/step
Epoch 108/150
4/4 - 0s - loss: 0.2468 - accuracy: 0.9714 - 13ms/epoch - 3ms/step
Epoch 109/150
4/4 - 0s - loss: 0.2451 - accuracy: 0.9714 - 15ms/epoch - 4ms/step
Epoch 110/150
4/4 - 0s - loss: 0.2426 - accuracy: 0.9714 - 12ms/epoch - 3ms/step
Epoch 111/150
4/4 - 0s - loss: 0.2404 - accuracy: 0.9714 - 11ms/epoch - 3ms/step
Epoch 112/150
4/4 - 0s - loss: 0.2387 - accuracy: 0.9714 - 11ms/epoch - 3ms/step
Epoch 113/150
4/4 - 0s - loss: 0.2365 - accuracy: 0.9619 - 10ms/epoch - 3ms/step
Epoch 114/150
4/4 - 0s - loss: 0.2343 - accuracy: 0.9714 - 10ms/epoch - 3ms/step
Epoch 115/150
4/4 - 0s - loss: 0.2327 - accuracy: 0.9714 - 12ms/epoch - 3ms/step
Epoch 116/150
4/4 - 0s - loss

In [47]:
predictions = model.predict(scaled_x_test).argmax(axis=1)

2/2 [==============================] - 0s 0s/step


In [48]:
print(predictions)

[1 0 2 1 1 0 1 2 2 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [49]:
Y_test = Y_test.argmax(axis=1)

In [50]:
Y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [51]:
print(accuracy_score(predictions,Y_test))

0.9777777777777777


In [54]:
print(confusion_matrix(predictions,Y_test))

[[19  0  0]
 [ 0 12  0]
 [ 0  1 13]]


In [55]:
print(classification_report(predictions,Y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      1.00      0.96        12
           2       1.00      0.93      0.96        14

   micro avg       0.98      0.98      0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [56]:
model.save('myfirstmodel.h5')

In [58]:
from keras.models import load_model

In [59]:
new_model = load_model('myfirstmodel.h5')

In [61]:
new_model.predict(scaled_x_test).argmax(axis=1)

2/2 [==============================] - 0s 0s/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)